package dev.typetype.server.services
import dev.typetype.server.models.AudioStreamItem
import dev.typetype.server.models.StreamResponse
import dev.typetype.server.models.SubtitleItem
import dev.typetype.server.models.VideoStreamItem
import org.schabi.newpipe.extractor.stream.StreamInfo
import org.schabi.newpipe.extractor.stream.StreamInfoItem
import org.schabi.newpipe.extractor.stream.SubtitlesStream

internal fun StreamInfo.toStreamResponse(): StreamResponse {
    val uploaded = uploadDate?.offsetDateTime()?.toInstant()?.toEpochMilli() ?: -1L
    val liveMetadata = streamLiveMetadata(streamType, hlsUrl, dashMpdUrl)
    return StreamResponse(
        id = id,
        title = name ?: "",
        uploaderName = uploaderName ?: "",
        uploaderUrl = uploaderUrl ?: "",
        uploaderAvatarUrl = uploaderAvatarUrl ?: "",
        thumbnailUrl = thumbnailUrl.toAbsoluteUrl(),
        description = description?.content ?: "",
        duration = duration,
        viewCount = viewCount,
        likeCount = likeCount,
        dislikeCount = dislikeCount,
        uploadDate = textualUploadDate ?: "",
        uploaded = uploaded,
        publishedAt = PublishedAtMapper.fromUploaded(uploaded),
        uploaderSubscriberCount = uploaderSubscriberCount,
        uploaderVerified = isUploaderVerified,
        category = category ?: "",
        license = licence ?: "",
        visibility = privacy?.name?.lowercase() ?: "",
        tags = tags ?: emptyList(),
        streamType = liveMetadata.streamType,
        isLive = liveMetadata.isLive,
        isPostLive = liveMetadata.isPostLive,
        isLiveContent = liveMetadata.isLiveContent,
        hasLiveManifest = liveMetadata.hasLiveManifest,
        isShortFormContent = isShortFormContent,
        requiresMembership = requiresMembership(),
        startPosition = startPosition,
        streamSegments = runCatching { streamSegments.map { it.toStreamSegmentItem() } }.getOrElse { emptyList() },
        hlsUrl = liveMetadata.hlsUrl,
        dashMpdUrl = liveMetadata.dashMpdUrl,
        videoStreams = videoStreams.map { it.toVideoStreamItem(id, false) }
            .filter { it.isSupportedPlaybackStream() },
        audioStreams = audioStreams.mapNotNull { runCatching { it.toAudioStreamItem(id) }.getOrNull() }
            .filter { it.isSupportedPlaybackStream() },
        originalAudioTrackId = null,
        preferredDefaultAudioTrackId = null,
        videoOnlyStreams = videoOnlyStreams.map { it.toVideoStreamItem(id, true) }
            .filter { it.isSupportedPlaybackStream() },
        subtitles = subtitles.mapNotNull { runCatching { it.toSubtitleItem() }.getOrNull() },
        previewFrames = previewFrames.mapNotNull { runCatching { it.toPreviewFrameItem() }.getOrNull() },
        sponsorBlockSegments = runCatching { getSponsorBlockSegments().map { it.toSegmentItem() } }.getOrElse { emptyList() },
        relatedStreams = relatedItems.filterIsInstance<StreamInfoItem>().mapNotNull { runCatching { it.toVideoItem() }.getOrNull() },
    )
}

internal fun SubtitlesStream.toSubtitleItem(): SubtitleItem = SubtitleItem(
    url = getContent() ?: "",
    mimeType = getFormat()?.getMimeType() ?: "",
    languageTag = getLanguageTag() ?: "",
    displayLanguageName = getDisplayLanguageName() ?: "",
    isAutoGenerated = isAutoGenerated,
)
