package dev.typetype.server.services

import dev.typetype.server.models.ExtractionResult
import dev.typetype.server.models.StreamResponse
import dev.typetype.server.models.SubtitleItem
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.TimeoutCancellationException
import kotlinx.coroutines.withTimeout
import okhttp3.HttpUrl.Companion.toHttpUrlOrNull

internal fun interface YouTubeSubtitleTrackResolver {
    suspend fun resolve(selection: YouTubeSubtitleSelection): YouTubeSubtitleResolution
}

internal class StreamYouTubeSubtitleResolver(
    private val streamService: StreamService,
    private val fetchInventory: suspend (String) -> YouTubeSubtitleInventoryResult,
) : YouTubeSubtitleTrackResolver {
    override suspend fun resolve(selection: YouTubeSubtitleSelection): YouTubeSubtitleResolution = try {
        withTimeout(RESOLUTION_TIMEOUT_MS) {
            val stream = streamService.streamForSubtitle(selection.videoId)
            val inventory = fetchInventory(selection.videoId)
            val tracks = (inventory as? YouTubeSubtitleInventoryResult.Ready)?.tracks
                ?.takeIf(List<SubtitleItem>::isNotEmpty)
                ?: stream?.subtitles
                ?: return@withTimeout YouTubeSubtitleResolution.Unavailable
            val track = tracks.firstOrNull { it.matchesYouTubeSubtitle(selection) }
                ?: return@withTimeout YouTubeSubtitleResolution.NotFound
            val content = track.contentForYouTubeSubtitle(selection)
                ?: return@withTimeout YouTubeSubtitleResolution.NotFound
            YouTubeSubtitleResolution.Ready(
                ResolvedYouTubeSubtitle(
                    content = content,
                    isUrl = true,
                    isLive = stream?.isLiveSubtitleContent() == true,
                ),
            )
        }
    } catch (_: TimeoutCancellationException) {
        YouTubeSubtitleResolution.Unavailable
    } catch (error: CancellationException) {
        throw error
    } catch (_: Throwable) {
        YouTubeSubtitleResolution.Unavailable
    }

    private companion object {
        const val RESOLUTION_TIMEOUT_MS = 30_000L
    }
}

private suspend fun StreamService.streamForSubtitle(videoId: String): StreamResponse? =
    when (val result = getStreamInfo("https://www.youtube.com/watch?v=$videoId")) {
        is ExtractionResult.Success -> result.data
        is ExtractionResult.BadRequest, is ExtractionResult.Failure -> null
    }

private fun StreamResponse.isLiveSubtitleContent(): Boolean = isLive || isLiveContent

internal fun SubtitleItem.matchesYouTubeSubtitle(selection: YouTubeSubtitleSelection): Boolean {
    val parsedUrl = url.toHttpUrlOrNull()
    val sourceLanguage = parsedUrl?.queryParameter("lang") ?: languageTag
    val requestedSource = selection.sourceLanguage ?: selection.language
    if (!sourceLanguage.equals(requestedSource, ignoreCase = true) &&
        !languageTag.equals(selection.language, ignoreCase = true)
    ) return false
    val auto = isAutoGenerated || parsedUrl?.queryParameter("kind") == "asr" ||
        parsedUrl?.queryParameter("vssId")?.startsWith("a.") == true
    if (auto != (selection.variant == YouTubeSubtitleVariant.Auto)) return false
    return selection.trackName == null || parsedUrl?.queryParameter("name") == selection.trackName
}

internal fun SubtitleItem.contentForYouTubeSubtitle(selection: YouTubeSubtitleSelection): String? {
    val parsedUrl = url.toHttpUrlOrNull()?.takeIf { isYouTubeTimedTextUrl(it.toString()) } ?: return null
    return parsedUrl.newBuilder()
        .setQueryParameter("fmt", selection.format.value)
        .apply {
            if (selection.translationLanguage == null) removeAllQueryParameters("tlang")
            else setQueryParameter("tlang", selection.translationLanguage)
        }
        .build()
        .toString()
}
