package dev.typetype.server.services

data class HomeRecommendationProfile(
    val seenUrls: Set<String>,
    val blockedVideos: Set<String>,
    val blockedChannels: Set<String>,
    val blockedKeywords: Set<String> = emptySet(),
    val feedbackBlockedVideos: Set<String>,
    val feedbackBlockedChannels: Set<String>,
    val subscriptionChannels: Set<String>,
    val favoriteUrls: Set<String>,
    val watchLaterUrls: Set<String>,
    val keywordAffinity: Set<String>,
    val themeTokens: Set<String>,
    val themeQueries: List<String>,
    val channelInterest: Map<String, Double> = emptyMap(),
    val topicInterest: Map<String, Double> = emptyMap(),
    val eventPenaltyByVideo: Map<String, Double> = emptyMap(),
    val implicitBlockedVideos: Set<String> = emptySet(),
    val subscriptionEngagement: Double = 0.0,
    val discoveryEngagement: Double = 0.0,
    val feedHistory: Map<String, RecommendationFeedHistoryEntry> = emptyMap(),
    val rejectionTopicPenalty: Map<String, Double> = emptyMap(),
    val rejectionChannelPenalty: Map<String, Double> = emptyMap(),
    val channelTopicProfile: Map<String, Map<String, Double>> = emptyMap(),
    val shortsTopicInterest: Map<String, Double> = emptyMap(),
    val rejectionTopicPairPenalty: Map<String, Double> = emptyMap(),
    val creatorMomentum: Map<String, Double> = emptyMap(),
    val delayedVideoCredit: Map<String, Double> = emptyMap(),
    val delayedChannelCredit: Map<String, Double> = emptyMap(),
    val shortPenaltyByVideo: Map<String, Double> = emptyMap(),
    val personalizationEnabled: Boolean = true,
)
