package dev.typetype.server.services

import dev.typetype.server.models.ExtractionResult
import dev.typetype.server.models.SubtitleItem
import dev.typetype.server.testStreamResponse
import kotlinx.coroutines.runBlocking
import okhttp3.HttpUrl.Companion.toHttpUrl
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class StreamYouTubeSubtitleResolverTest {
    @Test
    fun `resolution uses fresh inventory and preserves live state`() = runBlocking {
        val resolver = StreamYouTubeSubtitleResolver(
            streamService = streamService(
                listOf(track("https://www.youtube.com/api/timedtext?v=abcdefghijk&lang=de", false)),
                isLive = true,
            ),
            fetchInventory = {
                YouTubeSubtitleInventoryResult.Ready(
                    listOf(track("https://www.youtube.com/api/timedtext?v=abcdefghijk&lang=en", false)),
                )
            },
        )

        val result = resolver.resolve(selection(YouTubeSubtitleVariant.Manual))

        val ready = result as YouTubeSubtitleResolution.Ready
        assertTrue(ready.track.isLive)
        assertEquals("en", ready.track.content.toHttpUrl().queryParameter("lang"))
    }

    @Test
    fun `stream inventory is used when fresh inventory is unavailable`() = runBlocking {
        val resolver = StreamYouTubeSubtitleResolver(
            streamService = streamService(
                listOf(track("https://www.youtube.com/api/timedtext?v=abcdefghijk&lang=en", false)),
            ),
            fetchInventory = { YouTubeSubtitleInventoryResult.Unavailable },
        )

        assertTrue(resolver.resolve(selection(YouTubeSubtitleVariant.Manual)) is YouTubeSubtitleResolution.Ready)
    }

    @Test
    fun `manual and automatic tracks remain distinct`() {
        val manual = track("https://www.youtube.com/api/timedtext?v=abcdefghijk&lang=en", false)
        val automatic = track("https://www.youtube.com/api/timedtext?v=abcdefghijk&lang=en&kind=asr", true)

        assertTrue(manual.matchesYouTubeSubtitle(selection(YouTubeSubtitleVariant.Manual)))
        assertFalse(manual.matchesYouTubeSubtitle(selection(YouTubeSubtitleVariant.Auto)))
        assertTrue(automatic.matchesYouTubeSubtitle(selection(YouTubeSubtitleVariant.Auto)))
        assertFalse(automatic.matchesYouTubeSubtitle(selection(YouTubeSubtitleVariant.Manual)))
    }

    @Test
    fun `translated selection preserves source language and requested translation`() {
        val track = track(
            "https://www.youtube.com/api/timedtext?v=abcdefghijk&lang=en&kind=asr&tlang=de",
            true,
        )
        val selection = selection(YouTubeSubtitleVariant.Auto).copy(
            language = "fr",
            sourceLanguage = "en",
            translationLanguage = "fr",
        )

        assertTrue(track.matchesYouTubeSubtitle(selection))
        val resolved = requireNotNull(track.contentForYouTubeSubtitle(selection)).toHttpUrl()
        assertEquals("en", resolved.queryParameter("lang"))
        assertEquals("fr", resolved.queryParameter("tlang"))
        assertEquals("vtt", resolved.queryParameter("fmt"))
    }

    private fun streamService(subtitles: List<SubtitleItem>, isLive: Boolean = false) = object : StreamService {
        override suspend fun getStreamInfo(url: String) = ExtractionResult.Success(
            testStreamResponse().copy(subtitles = subtitles, isLive = isLive, isLiveContent = isLive),
        )
    }

    private fun track(url: String, automatic: Boolean) = SubtitleItem(
        url = url,
        mimeType = "application/ttml+xml",
        languageTag = "en",
        displayLanguageName = "English",
        isAutoGenerated = automatic,
    )

    private fun selection(variant: YouTubeSubtitleVariant) = YouTubeSubtitleSelection(
        videoId = "abcdefghijk",
        language = "en",
        variant = variant,
        format = YouTubeSubtitleFormat.Vtt,
    )
}
