ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        maxInitialLineLength = 65536
        maxHeaderSize = 65536
    }
    application {
        modules = [ dev.typetype.server.ApplicationKt.module ]
    }
}
