package dev.typetype.server.models

import kotlinx.serialization.Serializable

@Serializable
data class SubtitleItem(
    val url: String,
    val mimeType: String,
    val languageTag: String,
    val displayLanguageName: String,
    val isAutoGenerated: Boolean,
)
