package dev.typetype.server.models

import kotlinx.serialization.Serializable

@Serializable
data class StreamResponse(
    val id: String,
    val title: String,
    val uploaderName: String,
    val uploaderUrl: String,
    val uploaderAvatarUrl: String,
    val thumbnailUrl: String,
    val description: String,
    val duration: Long,
    val viewCount: Long,
    val likeCount: Long,
    val dislikeCount: Long,
    val uploadDate: String,
    val uploaded: Long,
    val uploaderSubscriberCount: Long,
    val uploaderVerified: Boolean,
    val category: String,
    val license: String,
    val visibility: String,
    val tags: List<String>,
    val streamType: String,
    val isShortFormContent: Boolean,
    val requiresMembership: Boolean,
    val startPosition: Long,
    val streamSegments: List<StreamSegmentItem>,
    val hlsUrl: String,
    val dashMpdUrl: String,
    val videoStreams: List<VideoStreamItem>,
    val audioStreams: List<AudioStreamItem>,
    val originalAudioTrackId: String?,
    val preferredDefaultAudioTrackId: String?,
    val videoOnlyStreams: List<VideoStreamItem>,
    val subtitles: List<SubtitleItem>,
    val previewFrames: List<PreviewFrameItem>,
    val sponsorBlockSegments: List<SponsorBlockSegmentItem>,
    val relatedStreams: List<VideoItem>,
    val publishedAt: Long? = null,
    val isLive: Boolean = false,
    val isPostLive: Boolean = false,
    val isLiveContent: Boolean = false,
    val hasLiveManifest: Boolean = false,
)
