package dev.typetype.server

import dev.typetype.server.services.toPreviewFrameItem
import dev.typetype.server.services.toStreamSegmentItem
import dev.typetype.server.services.toSubtitleItem
import io.mockk.every
import io.mockk.mockk
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test
import org.schabi.newpipe.extractor.stream.Frameset
import org.schabi.newpipe.extractor.stream.StreamSegment
import org.schabi.newpipe.extractor.stream.SubtitlesStream

class StreamInfoTimelineMappersTest {
    @Test
    fun `subtitle preview and segment mapping preserve payload`() {
        val subtitle = mockk<SubtitlesStream>()
        every { subtitle.getContent() } returns "https://example.com/sub.vtt"
        every { subtitle.getFormat() } returns null
        every { subtitle.getLanguageTag() } returns "en"
        every { subtitle.getDisplayLanguageName() } returns "English"
        every { subtitle.isAutoGenerated } returns true
        val mappedSubtitle = subtitle.toSubtitleItem()
        assertEquals("en", mappedSubtitle.languageTag)
        assertEquals("English", mappedSubtitle.displayLanguageName)
        val frameset = mockk<Frameset>()
        every { frameset.getUrls() } returns listOf("u1", "u2")
        every { frameset.getFrameWidth() } returns 160
        every { frameset.getFrameHeight() } returns 90
        every { frameset.getTotalCount() } returns 20
        every { frameset.getDurationPerFrame() } returns 5
        every { frameset.getFramesPerPageX() } returns 5
        every { frameset.getFramesPerPageY() } returns 4
        val mappedFrame = frameset.toPreviewFrameItem()
        assertEquals(20, mappedFrame.totalCount)
        assertEquals(2, mappedFrame.urls.size)
        val segment = mockk<StreamSegment>()
        every { segment.getTitle() } returns "Intro"
        every { segment.getStartTimeSeconds() } returns 15
        every { segment.getChannelName() } returns "Channel"
        every { segment.getUrl() } returns "https://example.com/chapter"
        every { segment.getPreviewUrl() } returns "https://example.com/preview.jpg"
        val mappedSegment = segment.toStreamSegmentItem()
        assertEquals("Intro", mappedSegment.title)
        assertEquals(15, mappedSegment.startTimeSeconds)
    }
}
