package dev.typetype.server

import dev.typetype.server.models.AudioStreamItem
import dev.typetype.server.models.VideoItem
import dev.typetype.server.models.VideoStreamItem

fun testVideoStream(
    url: String = "https://example.googlevideo.com/videoplayback?id=1",
    codec: String? = "avc1.42c01e",
    format: String = "MPEG_4",
    resolution: String = "720p",
    bitrate: Int = 2000000,
    width: Int = 1280,
    height: Int = 720,
    indexStart: Long = 221,
    indexEnd: Long = 893,
    initStart: Long = 0,
    initEnd: Long = 220,
    itag: Int = 137,
): VideoStreamItem = VideoStreamItem(
    url = url,
    mimeType = "video/mp4",
    format = format,
    resolution = resolution,
    bitrate = bitrate,
    codec = codec,
    isVideoOnly = true,
    itag = itag,
    width = width,
    height = height,
    fps = 30,
    contentLength = 10_000_000,
    initStart = initStart,
    initEnd = initEnd,
    indexStart = indexStart,
    indexEnd = indexEnd,
)

fun testAudioStream(
    url: String = "https://example.googlevideo.com/audioplayback?id=1",
    codec: String? = "mp4a.40.2",
    format: String = "M4A",
    bitrate: Int = 128,
    indexStart: Long = 100,
    indexEnd: Long = 500,
    initStart: Long = 0,
    initEnd: Long = 99,
    audioTrackId: String? = null,
    audioTrackName: String? = null,
    audioLocale: String? = null,
    isOriginal: Boolean = false,
    itag: Int = 140,
    deliveryMethod: String = "progressive",
    manifestUrl: String? = null,
    sabrSessionUrl: String? = null,
    contentLength: Long = 5_000_000,
): AudioStreamItem = AudioStreamItem(
    url = url,
    mimeType = "audio/mp4",
    format = format,
    bitrate = bitrate,
    codec = codec,
    quality = "medium",
    itag = itag,
    contentLength = contentLength,
    initStart = initStart,
    initEnd = initEnd,
    indexStart = indexStart,
    indexEnd = indexEnd,
    audioTrackId = audioTrackId,
    audioTrackName = audioTrackName,
    audioLocale = audioLocale,
    isOriginal = isOriginal,
    deliveryMethod = deliveryMethod,
    manifestUrl = manifestUrl,
    sabrSessionUrl = sabrSessionUrl,
)
